<?php

namespace Sorabji\PatientBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends DocumentRepository
{
}