imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   %test_database_driver%
        # driver:   pdo_sqlite
        host:     %test_database_host%
        port:     %test_database_port%
        dbname:   %test_database_name%
        user:     %test_database_user%
        password: %test_database_password%
        charset:  UTF8
        # path: %kernel.root_dir%/%test_database_name%
        # memory: true
